### ISSUE TITLE
cwdaemon.c:(.text.startup+0xa68): undefined reference to `cw_set_debug_flags'

### ISSUE THREAD

**Issue by UgoPoddine** [acerion/cwdaemon#4]
Hello,

trying to compile cwdaemon on a RaspberryPI3 with up-to-date Raspbian Buster, after correct ./configure execution, I'm getting the error :

cwdaemon.c:(.text.startup+0xa68): undefined reference to `cw_set_debug_flags'

unixcw-code should be installed correctly

Can you help ? Thank-you !

Best regards
IU1IPB Ugo

**Comment by acerion** [comment]
Hello,

Please tell me which version of cwdaemon are you trying to compile and which version of libcw library from unixcw package you have installed (please provide exact version number of either the library or unixcw package).

As you can see in the README for cwdaemon, the current version of the package (0.10.2) has been compiled against libcw version 6.5.1. This library version comes from unixcw package 3.5.0.

Best regards,
Kamil

**Comment by UgoPoddine** [comment]
Hello Kamil, 

Thank-you for your answer.
Unfortunately libcw version is 6.6.1.
Cwdaemon is at the last one available on git, it should be 0.10.2 from readme file.

Any support will be appreciated 
Best regards
Ugo


Il giorno 28 Lug 2020, 21:21, alle ore 21:21, acerion <notifications@github.com> ha scritto:

**Comment by UgoPoddine** [comment]
Hello Kamil,

I have : 
1) downloaded the previous version of unixcw  / libcw
2) installed it in quite trickly way due to incomplete makefile, referencing old version of automake 
3) finally compiling successfully cwdaemon

Surely not a "beginner" trip. 
In any case thank-you again for your support.

Best regards
Ugo
