### ISSUE TITLE
RTS for CW?

### ISSUE THREAD

**Issue by miken2em** [acerion/cwdaemon#5]
My LD-C103 (USB-to-RS-232-to-phone-plug-for-key-jack device) wants to send CW via RTS. cwdaemon uses DTR, and uses RTS for PTT. I suggest that there be a configuration option to allow CW to be sent over either pin. Otherwise, cwdaemon cannot be used with at least some models of LD-C103. The LD-C103 itself is not configurable.

**Comment by acerion** [comment]
On 15.08.2021 23:00, miken2em wrote:
> My LD-C103 (USB-to-RS-232-to-phone-plug-for-key-jack device) wants to 
> send CW via RTS. cwdaemon uses DTR, and uses RTS for PTT. I suggest that 
> there be a configuration option to allow CW to be sent over either pin. 
> Otherwise, cwdaemon cannot be used with at least some models of LD-C103. 
> The LD-C103 itself is not configurable.
> 

Hi!

Some time ago I have received a similar request from other user. He had 
shared a link to a discussion where a solution in source code is being 
discussed:

https://forums.qrz.com/index.php?threads/cw-keyer-with-no-dtr-pin-cwdaemon-cwlib.744068/#post-5732680

Right now I'm not planning a new release of cwdaemon, but when I finally 
get to working on the new release, such feature will certainly be included.

Best regards,
Kamil

**Comment by acerion** [comment]
Please try the new "-o" option that has been added in cwdaemon 0.11.0. Something like this should work for you:
-o key=RTS -o ptt=DTR

**Comment by acerion** [comment]
I'm closing this ticket.
The issue has been addressed with my last comment, and I haven't seen any follow-up messages since.
