### ISSUE TITLE
DTR left on

### ISSUE THREAD

**Issue by jmeloranta** [acerion/cwdaemon#7]
I am using DTR keying with cwdaemon. I am also running rigctld at the same time with these options:
--set-conf=data_bits=8,stop_bits=1,serial_parity=None,serial_handshake=None,dtr_state=Unset,rts_state=Unset
in order for it not to mess with the DTR line. Now if I turn the rig off and then back on then somehow the DTR line is UP all the time (and would key the rig until, for example, tlf is started that sends something to cwdaemon). This is a bit inconvenient behavior to have the rig keyed immediately when turned on. It is not clear to me if the DTR line is pulled up by rigctld or cwdaemon. Although the former is specifically instructed not to touch DTR.

**Comment by acerion** [comment]
I may have problems with recreating this problem soon, because right now I don't have access to a platform with serial port.
Meanwhile can you send me more details about your setup? Which version of cwdaemon and libcw are you using? Which HW platform are you using? I don't think that RPi has a serial port with DTR pin, but I may be wrong.

**Comment by jmeloranta** [comment]
libcw-dev/testing,now 3.6.0-5 arm64 [installed]
cwdaemon/testing,now 0.10.2-3 arm64 [installed]
I am using USB-RS232 dongle on the pi (raspi 4):
Bus 001 Device 003: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
Yes, I realize that this is likely HW dependent issue. I will try to get more clues what is going on.

**Comment by jmeloranta** [comment]
OK, this is not cwdaemon related. It has to do with rigctld (in my setup tlf controls the rig using this). Apparently this device (the USB rs dongle) has DTR set on by default when the device is opened. I had asked rigctld not to touch DTR. When I turn the rig off-on then rigctl reopens the device and the DTR goes up. I have to ask rigtctl to clear DTR signal rather than leave it alone. So, my configuration error - you can close this one. The correct option line to rigctld is:
--set-conf=data_bits=8,stop_bits=1,serial_parity=None,serial_handshake=None,**dtr_state=OFF**,rts_state=Unset

**Comment by acerion** [comment]
Thank you for checking and letting me know. I'm closing this ticket.
