### ISSUE TITLE
problem running configure

### ISSUE THREAD

**Issue by jmeloranta** [acerion/cwdaemon#8]
WIth the current git version, ./configure gives (at the end):
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating examples/Makefile
config.status: creating test/Makefile
config.status: error: cannot find input file: `test/library/Makefile.in'

So, perhaps the git repo is missing this file?

**Comment by acerion** [comment]
On 22.02.2022 05:31, Jussi Eloranta wrote:
> WIth the current git version, ./configure gives (at the end):
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating src/Makefile
> config.status: creating doc/Makefile
> config.status: creating examples/Makefile
> config.status: creating test/Makefile
> config.status: error: cannot find input file: `test/library/Makefile.in'
> 
> So, perhaps the git repo is missing this file?
> 
> —
Please try now, I have added the file.

**Comment by jmeloranta** [comment]
Yes, everything works now. Thank you - closing...
